name: Keep 18gps
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check trigger type
        run: |
          echo "📅 Trigger event: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "✅ AUTOMATIC RUN (cron)"
          else
            echo "👤 MANUAL RUN"
          fi
      
      - name: Ping
        run: |
          curl -s "https://18gps.net/TrackService.aspx?method=getUserAndGPSInfoUtc&school_id=43232166-a7d1-40a5-d100-5db4383c33ab&custid=43232166-a7d1-40a5-d100-5db4383c33ab&mds=2c8d7383278c4873ba9d4dbd560b1883&mapType=GOOGLE"
          curl -s "https://18gps.net/TrackService.aspx?method=getUserAndGPSInfoUtc&school_id=43232166-6084-a2a5-d100-24a41458b0bd&custid=43232166-6084-a2a5-d100-24a41458b0bd&mds=63c58e49ae6e4a03a9c015a2e5244e65&mapType=GOOGLE"