name: Keep 18gps Session

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Ping Account 1
        run: |
          curl -v \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" \
            -H "Accept-Language: en-US,en;q=0.5" \
            -H "Connection: keep-alive" \
            "https://18gps.net/user/index.aspx?login_id=43232166-6084-a2a5-d100-24a41458b0bd&mds=e63be868e32b4b1a8cba60ec372f4175&father_id=43232166-6084-a2a5-d100-24a41458b0bd&isDealer=false"
          
      - name: Ping Account 2
        run: |
          curl -v \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" \
            -H "Accept-Language: en-US,en;q=0.5" \
            -H "Connection: keep-alive" \
            "https://18gps.net/user/index.aspx?login_id=43232166-a7d1-40a5-d100-5db4383c33ab&mds=95402f3160ca45ae860717f0e2b71325&father_id=43232166-a7d1-40a5-d100-5db4383c33ab&isDealer=false"